import traces from './scriptTraces.json'

export type ScriptStroke = {
  /** One pen stroke, as a single-subpath SVG path. */
  d: string
  /** Its length in the same units as the viewBox, for timing the draw-on. */
  length: number
}

export type ScriptTrace = {
  text: string
  /**
   * Covers the ink, which reaches outside the text box where a flourish does —
   * an SVG clips to its viewBox, so the box has to be big enough for it.
   */
  viewBox: string
  /** Width/height and position as multiples of the font size, so the SVG scales
   *  with the line and still lines up with where the text sat. */
  widthRatio: number
  heightRatio: number
  offsetLeftRatio: number
  offsetTopRatio: number
  /** Average ink width at `FONT_SIZE`, i.e. the weight to draw the stroke at. */
  strokeWidth: number
  totalLength: number
  points: number
  /**
   * The pen strokes in reading order. Kept separate because `stroke-dasharray`
   * restarts per subpath — in one path they would all draw at once instead of
   * writing left to right.
   */
  strokes: ScriptStroke[]
}

const byText = new Map<string, ScriptTrace>(
  (traces as ScriptTrace[]).map((trace) => [trace.text, trace])
)

/**
 * The traced pen path for a hero script line.
 *
 * The script line is editable CMS text, but a path is tied to exact wording — so
 * this returns null for anything without a trace (an edited line, a new page)
 * and the hero falls back to setting the line in the font. Editing the script
 * in the CMS therefore degrades to the old fade rather than breaking.
 *
 * Traces are generated by `scripts/_trace.mjs`; re-run it if a line changes.
 */
export function scriptTrace(text: string): ScriptTrace | null {
  return byText.get(text.trim()) ?? null
}
