/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    disciplines: Discipline;
    'process-steps': ProcessStep;
    'event-types': EventType;
    testimonials: Testimonial;
    clients: Client;
    galleryItems: GalleryItem;
    formSubmissions: FormSubmission;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    'process-steps': ProcessStepsSelect<false> | ProcessStepsSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    galleryItems: GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    formSubmissions: FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'backstage-page': BackstagePage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'backstage-page': BackstagePageSelect<false> | BackstagePageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins can manage users and delete content. Editors can add and edit content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The event types Full Circle produces — one card each, plus a detail page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Which filter the card appears under on the Services page.
   */
  group: 'corporate' | 'entertainment' | 'community' | 'technical';
  /**
   * One or two sentences shown on the card and at the top of the detail page.
   */
  summary: string;
  /**
   * Portrait image, roughly 4:5. Shown on the card and detail hero.
   */
  image: number | Media;
  /**
   * The main content of the service detail page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  /**
   * Used in the page address. Generated from the title if left blank.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images for services, gallery and pages. Upload at the largest size you have.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines.
   */
  alt: string;
  /**
   * Optional text shown beneath the image in galleries.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Audio, Visual and Infrastructure — the cards on the home and services pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: number;
  title: string;
  /**
   * The paragraph under the title.
   */
  summary: string;
  /**
   * The dot-list under the summary.
   */
  points?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The looping animation shown above the title on the Services page.
   */
  animation: 'audio' | 'visual' | 'infrastructure';
  /**
   * The photograph shown on this discipline’s card on the home page.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The steps in the “Every event comes full circle” timeline on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps".
 */
export interface ProcessStep {
  id: number;
  /**
   * The step number shown above the title, e.g. 01.
   */
  number: string;
  title: string;
  body: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Event types — the home page marquee and the contact form buttons.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: number;
  label: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client quotes shown in the slider on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * Shown in green under the quote, e.g. “Cllr Ian Jones”.
   */
  name: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client or partner logos shown in the ticker on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo: number | Media;
  /**
   * Optional link for the logo.
   */
  url?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photographs shown on the Backstage page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems".
 */
export interface GalleryItem {
  id: number;
  image: number | Media;
  /**
   * Shown on the tile and in the lightbox, e.g. “Business Awards 2024”.
   */
  caption: string;
  /**
   * Which filter this photo lives under.
   */
  category: 'awards' | 'live' | 'community' | 'crew';
  /**
   * The shape of the tile in the grid. Match the photograph where you can.
   */
  aspectRatio:
    '16 / 9' | '3 / 2' | '4 / 3' | '1 / 1' | '472 / 636' | '742 / 832' | '400 / 554' | '588 / 425' | '742 / 831';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries from the contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Type of event, e.g. "Festival" or "Award ceremony".
   */
  eventType?: string | null;
  /**
   * Proposed event date, if given.
   */
  eventDate?: string | null;
  message: string;
  /**
   * The visitor agreed to be contacted.
   */
  consent: boolean;
  /**
   * URL of the page the form was submitted from.
   */
  sourcePage?: string | null;
  userAgent?: string | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'disciplines';
        value: number | Discipline;
      } | null)
    | ({
        relationTo: 'process-steps';
        value: number | ProcessStep;
      } | null)
    | ({
        relationTo: 'event-types';
        value: number | EventType;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'galleryItems';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'formSubmissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  group?: T;
  summary?: T;
  image?: T;
  body?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  points?:
    | T
    | {
        text?: T;
        id?: T;
      };
  animation?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-steps_select".
 */
export interface ProcessStepsSelect<T extends boolean = true> {
  number?: T;
  title?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  label?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleryItems_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  category?: T;
  aspectRatio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formSubmissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  eventType?: T;
  eventDate?: T;
  message?: T;
  consent?: T;
  sourcePage?: T;
  userAgent?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details and stats used across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  /**
   * Used in the footer copyright line.
   */
  legalName?: string | null;
  /**
   * Shown in the footer and meta tags.
   */
  tagline?: string | null;
  email: string;
  phone: string;
  address?: {
    street?: string | null;
    town?: string | null;
    county?: string | null;
    postcode?: string | null;
  };
  /**
   * Where “Get directions” points to.
   */
  mapsUrl?: string | null;
  /**
   * Latitude of the workshop, used to plot the location map. e.g. 53.4129 for Sheffield S9.
   */
  latitude?: number | null;
  /**
   * Longitude of the workshop, e.g. -1.4037 for Sheffield S9.
   */
  longitude?: number | null;
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  /**
   * Large numbers with a caption underneath.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 1200 × 630 image shown when a page is shared on social.
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The home page hero, sticky ticket and section headings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    headline1: string;
    headline2: string;
    /**
     * The green handwritten line, kept to a few words.
     */
    script: string;
    intro: string;
    image: number | Media;
    primary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
    secondary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
  };
  /**
   * The green card fixed to the bottom-right of the home page. It can be dismissed, and starts minimised on phones.
   */
  stickyTicket: {
    title: string;
    strap: string;
    line: string;
    cta: {
      label: string;
      href: string;
    };
  };
  howWeWork: {
    eyebrow: string;
    heading: string;
    intro: string;
  };
  services: {
    eyebrow: string;
    heading: string;
    intro: string;
  };
  aboutTeaser: {
    eyebrow: string;
    heading: string;
    body: string;
    image: number | Media;
    /**
     * Links to the About page.
     */
    linkLabel: string;
  };
  testimonials: {
    eyebrow: string;
    heading: string;
  };
  clients: {
    eyebrow: string;
    intro: string;
  };
  cta: {
    /**
     * The white part of the big headline.
     */
    heading: string;
    /**
     * The words at the end of the headline shown in green.
     */
    accent?: string | null;
    /**
     * Start the green words on a new line.
     */
    newLineBeforeAccent?: boolean | null;
    body?: string | null;
    /**
     * Full-bleed background photo for the panel.
     */
    image: number | Media;
    primary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
    secondary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
  };
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the About Us page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    headline1: string;
    headline2: string;
    script: string;
    intro: string;
    image: number | Media;
    /**
     * Short items separated by green rings, e.g. phone · email · postcode.
     */
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  whatWeDo: {
    eyebrow: string;
    heading: string;
    intro: string;
    /**
     * The two-column list with ring bullets.
     */
    capabilities?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The big numbered list down the right-hand side (01–07).
     */
    eventTypes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  history: {
    eyebrow: string;
    heading: string;
    image: number | Media;
    /**
     * Label shown under the left ring in the merge animation.
     */
    companyOne: string;
    /**
     * Label shown under the right ring in the merge animation.
     */
    companyTwo: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Large numbers with a caption underneath.
     */
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  location: {
    eyebrow: string;
    heading: string;
    body: string;
    address?: string | null;
    /**
     * Placed on the map from their real coordinates, so the directions and relative distances are correct.
     */
    towns?:
      | {
          name: string;
          /**
           * Real latitude, e.g. 53.3811 for Sheffield.
           */
          latitude: number;
          /**
           * Real longitude, e.g. -1.4701 for Sheffield.
           */
          longitude: number;
          /**
           * Blink delay, e.g. .5s.
           */
          delay?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  commitment: {
    eyebrow: string;
    heading: string;
    body: string;
    image: number | Media;
    pillars?:
      | {
          title: string;
          body: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    /**
     * The white part of the big headline.
     */
    heading: string;
    /**
     * The words at the end of the headline shown in green.
     */
    accent?: string | null;
    /**
     * Start the green words on a new line.
     */
    newLineBeforeAccent?: boolean | null;
    body?: string | null;
    /**
     * Full-bleed background photo for the panel.
     */
    image: number | Media;
    primary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
    secondary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
  };
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Services page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    headline1: string;
    headline2: string;
    script: string;
    intro: string;
    image: number | Media;
    /**
     * Short items separated by green rings, e.g. phone · email · postcode.
     */
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  disciplines: {
    eyebrow: string;
    heading: string;
    intro: string;
  };
  events: {
    eyebrow: string;
    heading: string;
  };
  cta: {
    /**
     * The white part of the big headline.
     */
    heading: string;
    /**
     * The words at the end of the headline shown in green.
     */
    accent?: string | null;
    /**
     * Start the green words on a new line.
     */
    newLineBeforeAccent?: boolean | null;
    body?: string | null;
    /**
     * Full-bleed background photo for the panel.
     */
    image: number | Media;
    primary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
    secondary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
  };
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Backstage (gallery) page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage-page".
 */
export interface BackstagePage {
  id: number;
  hero: {
    headline1: string;
    headline2: string;
    script: string;
    intro: string;
    image: number | Media;
    /**
     * Short items separated by green rings, e.g. phone · email · postcode.
     */
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  gallery: {
    eyebrow: string;
    heading: string;
  };
  cta: {
    /**
     * The white part of the big headline.
     */
    heading: string;
    /**
     * The words at the end of the headline shown in green.
     */
    accent?: string | null;
    /**
     * Start the green words on a new line.
     */
    newLineBeforeAccent?: boolean | null;
    body?: string | null;
    /**
     * Full-bleed background photo for the panel.
     */
    image: number | Media;
    primary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
    secondary: {
      label: string;
      /**
       * Where the button goes, e.g. /contact-us or /gallery.
       */
      href: string;
    };
  };
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    headline1: string;
    headline2: string;
    script: string;
    intro: string;
    image: number | Media;
    /**
     * Short items separated by green rings, e.g. phone · email · postcode.
     */
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  form: {
    eyebrow: string;
    heading: string;
    replyNote: string;
    consentLabel: string;
    errorMessage: string;
  };
  info: {
    ticketLine: string;
    ticketHeading: string;
    socialsLabel: string;
  };
  location: {
    eyebrow: string;
    heading: string;
    body: string;
    /**
     * Placed on the map from their real coordinates, so the directions and relative distances are correct.
     */
    towns?:
      | {
          name: string;
          /**
           * Real latitude, e.g. 53.3811 for Sheffield.
           */
          latitude: number;
          /**
           * Real longitude, e.g. -1.4701 for Sheffield.
           */
          longitude: number;
          /**
           * Blink delay, e.g. .5s.
           */
          delay?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * What Google and social previews show. Leave blank to use the page copy.
   */
  seo?: {
    /**
     * Just the page name, e.g. “About Us” — the site name is added after it.
     */
    title?: string | null;
    /**
     * One sentence, roughly 150 characters, describing the page. Shown under the title in search results.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  legalName?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        town?: T;
        county?: T;
        postcode?: T;
      };
  mapsUrl?: T;
  latitude?: T;
  longitude?: T;
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline1?: T;
        headline2?: T;
        script?: T;
        intro?: T;
        image?: T;
        primary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  stickyTicket?:
    | T
    | {
        title?: T;
        strap?: T;
        line?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  howWeWork?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
      };
  services?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
      };
  aboutTeaser?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        linkLabel?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  clients?:
    | T
    | {
        eyebrow?: T;
        intro?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        accent?: T;
        newLineBeforeAccent?: T;
        body?: T;
        image?: T;
        primary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline1?: T;
        headline2?: T;
        script?: T;
        intro?: T;
        image?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  whatWeDo?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        capabilities?:
          | T
          | {
              text?: T;
              id?: T;
            };
        eventTypes?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  history?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        image?: T;
        companyOne?: T;
        companyTwo?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  location?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        address?: T;
        towns?:
          | T
          | {
              name?: T;
              latitude?: T;
              longitude?: T;
              delay?: T;
              id?: T;
            };
      };
  commitment?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        image?: T;
        pillars?:
          | T
          | {
              title?: T;
              body?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        accent?: T;
        newLineBeforeAccent?: T;
        body?: T;
        image?: T;
        primary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline1?: T;
        headline2?: T;
        script?: T;
        intro?: T;
        image?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  disciplines?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
      };
  events?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        accent?: T;
        newLineBeforeAccent?: T;
        body?: T;
        image?: T;
        primary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage-page_select".
 */
export interface BackstagePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline1?: T;
        headline2?: T;
        script?: T;
        intro?: T;
        image?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  gallery?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  cta?:
    | T
    | {
        heading?: T;
        accent?: T;
        newLineBeforeAccent?: T;
        body?: T;
        image?: T;
        primary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline1?: T;
        headline2?: T;
        script?: T;
        intro?: T;
        image?: T;
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  form?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        replyNote?: T;
        consentLabel?: T;
        errorMessage?: T;
      };
  info?:
    | T
    | {
        ticketLine?: T;
        ticketHeading?: T;
        socialsLabel?: T;
      };
  location?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        body?: T;
        towns?:
          | T
          | {
              name?: T;
              latitude?: T;
              longitude?: T;
              delay?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}